### PR TITLE
proposed minor syntax and ws changes

### PR DESCRIPTION
**Pull request by gavinking**
@DiegoCoronel you're quite welcome to disregard these.

### CODE REVIEW

**Comment by DiegoCoronel** [comment]
more ceylonic ;)

**Comment by DiegoCoronel** [comment]
oops, theres a problem when persist now:
`Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: jaxrs.example.entity.Employee`  

Thats because the id is `-1`   

@gavinking do you have any suggestion to fix ou should i make the id back to `JInteger?`?

**Comment by gavinking** [comment]
Oh, sorry ... what happens if you change the default to 0 instead of -1?

**Comment by DiegoCoronel** [comment]
Yes, it worked :). Its commited, tks

**Pull request merged**
